### PR TITLE
update example app to demonstrate usage of IsolateNameServer so action can trigger navigation

### PR DESCRIPTION
**Pull request by MaikuB**
@ened this is show how background isolates can pass messages back to the main isolate and trigger navigation

### CODE REVIEW

**Comment by ened** [comment]
The clang-format action seems to remove symlinks and replace them with resolved files again. Could you restore the symlinks?

**Comment by MaikuB** [comment]
Afraid I don't know about too with the knowledge I have of doing development via Xcode

**Comment by MaikuB** [comment]
Also wouldn't trying to restore trigger the format action to kick in and remove the links again?

**Comment by ened** [comment]
> Also wouldn't trying to restore trigger the format action to kick in and remove the links again?

Yes. Here's what I do now, every time this happens:

```
ln -sf ../../darwin/Classes/Converters.h
ln -sf ../../darwin/Classes/Converters.m
```

What we need is this: https://github.com/CocoaPods/CocoaPods/issues/1259 or some shared framework.. or remove the need for the Converter files. Or fix clang-format. :-)

**Comment by ened** [comment]
Please rebase this branch, @MaikuB

**Comment by MaikuB** [comment]
@ened hopefully I've done it right :)

**Comment by ened** [comment]
@MaikuB please do it once more.. sorry!

**Comment by MaikuB** [comment]
No worries, tried to but looks like when I tried to do so it removed the sym link again urgh

**Comment by MaikuB** [comment]
Alright should be fine now 😅

**Pull request merged**
